### DISCUSSION TITLE
persisting a reference in a collection

### DISCUSSION THREAD

**Discussion by digitalkaoz** [vuejs/vuefire#1396] [Questions and Help] [answered]
hey, im struggeling to properly persist a reference inside a document.

assume this collections:

```yaml
user:
  xyz: {name: "Foo"}
  abc: {name: "Bar"}

entity:
  123:
    name: "123"
     users:
        - users/xyz
        - users/abc
```

now im trying to create a new entity:

```ts
const coll = collection("entity");
const userColl = collection("user");

const p = { name: "Foobar", users: [
  doc(userColl, "xyz"),
  doc(userColl, "abc"),
 ]}

await addDoc(coll, p);
```

but somehow its not working as expect, its not creating a clean reference like `<reference>users/xyz` but its creating a fullblown map with all properties from the doc object.

so how do i create references properly?
